# Generated by Django 5.1 on 2025-04-26 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Forms', '0001_initial'),
        ('main', '0013_machine_description_machine_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machinerecordparameter',
            name='captured_at',
        ),
        migrations.RemoveField(
            model_name='machinerecordparameter',
            name='operator',
        ),
        migrations.AlterField(
            model_name='machinerecordparameter',
            name='machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machine', to='main.machine'),
        ),
    ]
