# Generated by Django 5.1 on 2025-07-25 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Forms', '0002_remove_machinerecordparameter_captured_at_and_more'),
        ('laboratory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machinerecordparameter',
            name='machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machine', to='laboratory.machine'),
        ),
        migrations.CreateModel(
            name='LaberatoryFormsParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameters', models.JSONField(blank=True, default=dict)),
                ('Lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machine', to='laboratory.laberatory')),
            ],
        ),
    ]
