# Generated by Django 5.1 on 2025-07-25 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='model',
            field=models.TextField(default='…'),
        ),
        migrations.AddField(
            model_name='machine',
            name='serial_number',
            field=models.TextField(default='…'),
        ),
    ]
