# Generated by Django 5.1 on 2024-09-07 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_machine_laberatory_delete_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='form_template',
            field=models.TextField(default='add template'),
        ),
    ]
