# Generated by Django 5.1 on 2024-12-04 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_machine_lab_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='supervisor',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='supervisors',
            field=models.ManyToManyField(blank=True, related_name='employees', to='main.userprofile'),
        ),
    ]
