# Generated by Django 5.1 on 2024-12-04 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_userprofile_supervisor_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='supervisors',
            new_name='supervisor',
        ),
    ]
