# Generated by Django 5.1 on 2025-04-22 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='category',
            field=models.CharField(default='Research', max_length=20),
        ),
    ]
