# Generated by Django 5.1 on 2025-04-22 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_category_alter_machine_form_template_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Machine_Category',
        ),
    ]
