# Generated by Django 5.1 on 2025-04-22 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_rename_category_machine_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machine',
            name='category',
        ),
        migrations.DeleteModel(
            name='Machine_Category',
        ),
    ]
