# Generated by Django 5.1 on 2025-04-24 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_machine_category_machine_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='machine',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
