# Generated by Django 5.1 on 2025-07-25 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Forms', '0003_alter_machinerecordparameter_machine_and_more'),
        ('laboratory', '0001_initial'),
        ('main', '0013_machine_description_machine_status'),
        ('reports', '0026_alter_records_machine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='lab',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lab_team', to='laboratory.laberatory'),
        ),
        migrations.RemoveField(
            model_name='machine',
            name='lab',
        ),
        migrations.RemoveField(
            model_name='machine',
            name='category',
        ),
        migrations.AlterField(
            model_name='team',
            name='machine',
            field=models.ManyToManyField(blank=True, related_name='machine_team', to='laboratory.machine'),
        ),
        migrations.DeleteModel(
            name='Laberatory',
        ),
        migrations.DeleteModel(
            name='Machine',
        ),
        migrations.DeleteModel(
            name='Machine_Category',
        ),
    ]
