# Generated by Django 4.1.13 on 2025-07-29 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_team_lab_remove_machine_lab_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('technician', 'Technician'), ('scientist', 'Scientist'), ('laboratory_manager', 'Laboratory Manager'), ('manager', 'Manager')], default='technician', max_length=50),
        ),
    ]
