# Generated by Django 5.1 on 2024-09-04 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_machine_laberatory_delete_post'),
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='formula',
        ),
        migrations.CreateModel(
            name='Records',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField()),
                ('machine', models.ManyToManyField(to='main.machine')),
                ('report', models.ManyToManyField(to='reports.report')),
            ],
        ),
    ]
