# Generated by Django 5.1 on 2024-09-07 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_remove_report_formula_records'),
    ]

    operations = [
        migrations.AlterField(
            model_name='records',
            name='data',
            field=models.JSONField(blank=True),
        ),
        migrations.AlterField(
            model_name='records',
            name='report',
            field=models.ManyToManyField(related_name='reports', to='reports.report'),
        ),
    ]
