# Generated by Django 5.1 on 2024-09-07 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_machine_form_template'),
        ('reports', '0003_alter_records_data_alter_records_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='records',
            name='machine',
            field=models.ManyToManyField(related_name='machines', to='main.machine'),
        ),
    ]
