# Generated by Django 5.1 on 2024-09-07 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_machine_form_template'),
        ('reports', '0004_alter_records_machine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='records',
            name='machine',
            field=models.ManyToManyField(default=1, related_name='machines', to='main.machine'),
        ),
    ]
