# Generated by Django 5.1 on 2024-09-24 04:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_machine_lab_userprofile'),
        ('reports', '0007_report_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='records',
            name='report',
            field=models.ManyToManyField(related_name='reports_records', to='reports.report'),
        ),
        migrations.AlterField(
            model_name='report',
            name='prjct',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.project'),
        ),
    ]
