# Generated by Django 5.1 on 2024-09-30 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0009_report_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ['-date_added']},
        ),
        migrations.AlterField(
            model_name='report',
            name='date_added',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
