# Generated by Django 5.1 on 2024-09-30 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0010_alter_report_options_alter_report_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='tasks',
            name='due_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
