# Generated by Django 5.1 on 2024-09-30 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0011_tasks_created_at_tasks_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='due_date',
            field=models.DateTimeField(),
        ),
    ]
