# Generated by Django 5.1 on 2024-10-02 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0012_alter_tasks_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='records',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to="records_attachments/'"),
        ),
    ]
