# Generated by Django 5.1 on 2024-10-02 08:13

import django.db.models.deletion
import reports.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0013_records_attachment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='records',
            name='attachment',
        ),
        migrations.CreateModel(
            name='Records_attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment', models.FileField(blank=True, null=True, upload_to=reports.models.custom_upload_to)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='reports.records')),
            ],
        ),
    ]
