# Generated by Django 5.1 on 2024-10-02 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0014_remove_records_attachment_records_attachment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='records_attachment',
            old_name='attachment',
            new_name='attach',
        ),
    ]
