# Generated by Django 5.1 on 2024-10-02 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0015_rename_attachment_records_attachment_attach'),
    ]

    operations = [
        migrations.RenameField(
            model_name='records_attachment',
            old_name='attach',
            new_name='attachment',
        ),
    ]
