# Generated by Django 5.1 on 2024-10-02 09:21

import django.db.models.deletion
import reports.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0016_rename_attach_records_attachment_attachment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task_attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment', models.FileField(blank=True, null=True, upload_to=reports.models.custom_upload_to)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='reports.tasks')),
            ],
        ),
    ]
