# Generated by Django 5.1 on 2024-10-02 09:34

import reports.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0017_task_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task_attachment',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to=reports.models.task_custom_upload_to),
        ),
    ]
