# Generated by Django 5.1 on 2025-04-16 10:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_team'),
        ('reports', '0018_alter_task_attachment_attachment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task_attachment',
            options={'ordering': ('created',)},
        ),
        migrations.AddField(
            model_name='task_attachment',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tasks',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_task', to='main.team'),
        ),
        migrations.AddField(
            model_name='tasks',
            name='workers',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.IntegerField(default=1),
        ),
        migrations.CreateModel(
            name='Task_comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('body', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('Task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='reports.tasks')),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
