# Generated by Django 5.1 on 2025-04-16 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0019_alter_task_attachment_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasks',
            old_name='workers',
            new_name='workers_count',
        ),
    ]
