# Generated by Django 5.1 on 2025-04-17 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0020_rename_workers_tasks_workers_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='start_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
