# Generated by Django 5.1 on 2025-04-22 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0021_tasks_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='start_date',
            field=models.DateTimeField(default=True),
        ),
    ]
