# Generated by Django 5.1 on 2025-04-22 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0022_alter_tasks_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='created_at',
            field=models.DateTimeField(default=True),
        ),
    ]
