# Generated by Django 5.1 on 2025-04-23 08:18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0024_alter_tasks_created_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task_comment',
            name='active',
        ),
        migrations.RemoveField(
            model_name='task_comment',
            name='email',
        ),
        migrations.RemoveField(
            model_name='task_comment',
            name='name',
        ),
        migrations.RemoveField(
            model_name='task_comment',
            name='updated',
        ),
        migrations.AddField(
            model_name='task_comment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
