# Generated by Django 5.1 on 2025-07-25 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0001_initial'),
        ('reports', '0025_remove_task_comment_active_remove_task_comment_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='records',
            name='machine',
            field=models.ManyToManyField(default=1, related_name='machines', to='laboratory.machine'),
        ),
    ]
