# Generated by Django 4.1.13 on 2025-08-06 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0026_alter_records_machine'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='urgency',
            field=models.IntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High'), (4, 'Critical')], default=1),
        ),
    ]
