# Generated by Django 4.1.13 on 2025-12-22 13:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import reports.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('laboratory', '0003_machine_machine_responsible'),
        ('reports', '0028_tasks_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Machine_comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='laboratory.machine')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='Machine_attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to=reports.models.machine_custom_upload_to)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='laboratory.machine')),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
